ydc_develop/force-app/main/default/objects/BI__c/fields/Host_Name__c.field-meta.xml
<CustomField>
    <fullName>Host_Name__c</fullName>
    <label>Host Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ydc_develop/force-app/main/default/objects/BI__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <inlineHelpText>Password to login to the Tableau Server</inlineHelpText>
    <label>Password</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

ydc_develop/force-app/main/default/objects/BI__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <inlineHelpText>Coma separated list of sites</inlineHelpText>
    <label>Site</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ydc_develop/force-app/main/default/objects/BI__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <inlineHelpText>Username to login to Tableau Server</inlineHelpText>
    <label>Username</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ydc_develop/force-app/main/default/classes/CallTableauSyncAPI.cls
public class CallTableauSyncAPI {
    @auraEnabled
    public static BI__c call_Tab_API(id recid){
        BI__c BIServer = [select id,name, site__c, username__c, type__c, port__c, host_name__c, password__c 
                          from BI__c where id = :recid];
        system.debug('Inside Server Controller:'+BIServer);
        try{
      //  TableauMetadataSync sync=new TableauMetadataSync(BIServer.Username__c,BIServer.Password__c,BIServer.Host_Name__c,BIServer.Site__c,recid);
        //sync.sync();
        } catch(exception e){
            throw new AuraHandledException('Error:'+e);
        }
        
        return BIServer;
    }

}